mode: debug #启动模式 debug, release, test
port: :8080 #启动端口
name: apidemo-gin #服务名称
url: http://localhost #服务本地地址
max_ping_count: 10 #自检次数
# 数据库配置（mysql）
database:
  dbname: go_test #数据库名称
  host: 127.0.0.1 #数据库服务地址
  port: 3306 #数据库端口
  username: root #用户名(实际线上不可使用root,请授权一个账户)
  password: 123456 #密码
  maximum-pool-size: 300  #连接池最大连接数
  maximum-idle-size: 20  #连接池最大空闲数
  log-mode: true # 输出日志
# 缓存redis配置
redis:
  address: localhost:6379 #redis server地址
  password: 123456 #redis auth 密码，可选，默认无密码
  db: 0 #数据库，可选，默认0
  pool-size: 100 #同一时刻池中最大连接数
  min-idle-conns: 10 #建立连接时维持的最小空闲连接数量，避免新建连接速度慢
  idle-timeout: 3000 #最大空闲时长，单位是秒s
# 日志配置(使用zap&lumberjack)
log:
  level: debug
  file-name: web-server.log
  time-format: 2006-01-02 15:04:05.000
  max-size: 500 #单个日志文件大小MB
  max-backups: 7
  max-age: 7 #Days
  compress: true
  local-time: false
  console: true #是否打印到控制台

